name: ğŸš€ Deploy website on push
'on': push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        run: echo "hello world"
      - name: ğŸšš Get latest code1
        run: echo "hello w"
